version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: bullet
      POSTGRES_USER: bell
      POSTGRES_PASSWORD: cold
    ports:
      - "5433:5432"
