version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: bullet
      POSTGRES_USER: bell
      POSTGRES_PASSWORD: cold
    ports:
      - "5433:5432"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "bullet"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper