server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    config:
      name: bootstrap
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: API Gateway Global Filter
            preLogger: true
            postLogger: true

      routes:
        #============================user-service============================#
        - id: user-service
          uri: ${user_service_uri}
          predicates:
            - Path=/user-service/ping
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*),/api/v1/${segment}
        - id: user-service
          uri: ${user_service_uri}
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/api/v1/${segment}
        - id: user-service
          uri: ${user_service_uri}
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/api/v1/${segment}
        - id: user-service
          uri: ${user_service_uri}
          predicates:
            - Path=/user-service/reissue
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*),/api/v1/${segment}
        - id: user-service
          uri: ${user_service_uri}
          predicates:
            - Path=/user-service/logout
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/api/v1/${segment}
        - id: user-service
          uri: ${user_service_uri}
          predicates:
            - Path=/user-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

        #============================order-service============================#
        - id: order-service
          uri: ${order_service_uri}
          predicates:
            - Path=/order-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/order-service/(?<segment>.*),/api/v1/${segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 3
                key-resolver: "#{@tokenKeyResolver}"

token:
  secret: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=

user_service_uri: "http://localhost:8081"
order_service_uri: "http://localhost:8082"