server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    config:
      name: bootstrap
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: API Gateway Global Filter
            preLogger: true
            postLogger: true

      routes:
        - id: user-service
          uri: ${user_service_uri}
          predicates:
            - Path=/user-service/ping
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*),/api/v1/${segment}
        - id: user-service
          uri: ${user_service_uri}
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/api/v1/${segment}
        - id: user-service
          uri: ${user_service_uri}
          predicates:
            - Path=/user-service/reissue
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*),/api/v1/${segment}
        - id: user-service
          uri: ${user_service_uri}
          predicates:
            - Path=/user-service/logout
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/api/v1/${segment}
        - id: user-service
          uri: ${user_service_uri}
          predicates:
            - Path=/user-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

token:
  secret: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=

user_service_uri: "http://localhost:8081"