server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: bell
    password: cold

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true

token:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  secret: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
  refresh-token-name: refresh-token
  access-token-name: access-token