server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: bell
    password: cold

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  kafka:
    admin:
      security:
        protocol: SSL

  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:sql/data.sql

kafka:
  host: 127.0.0.1
  port: 9092