server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pay
    username: bell
    password: cold

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true

kafka:
  host: 127.0.0.1
  port: 9092